import React, { useState, useRef, useEffect } from 'react';

const initialMessages = [
    {
        from: 'bot',
        text: 'Hi, I am the MediVault assistant. I can help you with questions like how to book an appointment, login, or understand how MediVault works.',
    },
];

const Chatbot = ({ isDark }) => {
    const [isOpen, setIsOpen] = useState(false);
    const [messages, setMessages] = useState(initialMessages);
    const [input, setInput] = useState('');
    const messagesEndRef = useRef(null);

    useEffect(() => {
        if (messagesEndRef.current) {
            messagesEndRef.current.scrollIntoView({ behavior: 'smooth' });
        }
    }, [messages, isOpen]);

    const toggleOpen = () => {
        setIsOpen(prev => {
            const next = !prev;
            if (!next) {
                setMessages(initialMessages);
                setInput('');
            }
            return next;
        });
    };

    const handleSend = (e) => {
        e.preventDefault();
        const trimmed = input.trim();
        if (!trimmed) return;

        const userMessage = { from: 'user', text: trimmed };
        setMessages(prev => [...prev, userMessage]);
        setInput('');

        const reply = getBotReply(trimmed);
        setTimeout(() => {
            setMessages(prev => [...prev, { from: 'bot', text: reply }]);
        }, 300);
    };

    const getBotReply = (question) => {
        const q = question.toLowerCase();

        if (q.includes('book') && q.includes('appointment')) {
            return 'To book an appointment: 1) Login or register as a patient. 2) Go to your Patient Dashboard. 3) Select a hospital and doctor. 4) Request an appointment and complete the payment if required. 5) You will see the status of your appointment in the dashboard.';
        }

        if ((q.includes('how many') || q.includes('number of')) && (q.includes('doctor') || q.includes('doctors'))) {
            return 'MediVault connects you with multiple registered doctors from different specialties. After login, you can see available doctors for each hospital in your Patient Dashboard.';
        }

        if ((q.includes('how many') || q.includes('number of')) && (q.includes('hospital') || q.includes('hospitals'))) {
            return 'MediVault supports multiple partner hospitals. Once you login, you can see the list of hospitals that are active and available for booking.';
        }

        if (q.includes('what is medivault') || (q.includes('about') && q.includes('medivault'))) {
            return 'MediVault is a secure medical records and appointment management platform for patients, doctors, and hospitals. Patients can view reports, download consultation PDFs, and manage appointments in one place.';
        }

        if (q.includes('login') || q.includes('sign in')) {
            return 'Click on the Login button on the top-right or on the home page, choose your role (Patient / Hospital / Doctor / Admin), and enter your registered username and password.';
        }

        if (q.includes('register') || q.includes('sign up') || q.includes('create account')) {
            return 'Patients can create a new account from the registration option on the Login page. Hospitals and doctors are usually created by the admin or hospital team.';
        }

        if (q.includes('report') || q.includes('pdf') || q.includes('download')) {
            return 'After login as a patient, go to your Patient Dashboard. There you can view your past consultations and download PDF reports generated by your doctors.';
        }

        if (q.includes('payment') || q.includes('fees') || q.includes('pay')) {
            return 'When you request an appointment, you may be asked to pay the consultation fees online. After a successful payment, your appointment will be confirmed and visible in your Patient Dashboard.';
        }

        if (q.includes('help') || q.includes('support') || q.includes('contact')) {
            return 'For any issues related to MediVault, you can contact your hospital or administrator. If something is not working on the website, please try again later or contact the support email shown on the contact or about pages.';
        }

        if (q.includes('feature') || q.includes('what can you do') || q.includes('what can i do')) {
            return 'With MediVault, patients can view and download medical reports, manage appointments, and see consultation history. Hospitals and doctors can manage patient records, create consultation notes, and upload files securely.';
        }

        return 'I am not sure about that yet. You can ask me things like: "How to book appointment?", "How many doctors and hospitals?", "How to login?", or "How to download reports?"';
    };

    const styles = getStyles(isDark);

    return (
        <>
            {isOpen && (
                <div style={styles.panel}>
                    <div style={styles.header}>
                        <span>MediVault Assistant</span>
                        <button type="button" style={styles.closeButton} onClick={toggleOpen}>
                            
                        </button>
                    </div>
                    <div style={styles.body}>
                        <div style={styles.messagesContainer}>
                            {messages.map((m, idx) => (
                                <div
                                    key={idx}
                                    style={m.from === 'user' ? styles.userMessageWrapper : styles.botMessageWrapper}
                                >
                                    <div style={m.from === 'user' ? styles.userMessage : styles.botMessage}>
                                        {m.text}
                                    </div>
                                </div>
                            ))}
                            <div ref={messagesEndRef} />
                        </div>
                        <form style={styles.inputRow} onSubmit={handleSend}>
                            <input
                                type="text"
                                style={styles.input}
                                placeholder="Ask about MediVault..."
                                value={input}
                                onChange={(e) => setInput(e.target.value)}
                            />
                            <button type="submit" style={styles.sendButton}>
                                Send
                            </button>
                        </form>
                    </div>
                </div>
            )}

            <button type="button" style={styles.fab} onClick={toggleOpen}>
                <span style={{ fontSize: '1.2rem', marginRight: '0.3rem' }}>
                    
                </span>
                <span>Chat</span>
            </button>
        </>
    );
};

const getStyles = (isDark) => ({
    fab: {
        position: 'fixed',
        right: '1.75rem',
        bottom: '1.75rem',
        zIndex: 1000,
        borderRadius: '999px',
        border: 'none',
        padding: '0.75rem 1.4rem',
        display: 'flex',
        alignItems: 'center',
        backgroundColor: isDark ? '#16a34a' : '#22c55e',
        color: '#ffffff',
        fontWeight: 600,
        boxShadow: '0 12px 30px rgba(15, 23, 42, 0.45)',
        cursor: 'pointer',
    },
    panel: {
        position: 'fixed',
        right: '1.75rem',
        bottom: '5.25rem',
        width: '320px',
        maxHeight: '420px',
        borderRadius: '18px',
        overflow: 'hidden',
        boxShadow: '0 20px 50px rgba(15, 23, 42, 0.50)',
        backgroundColor: isDark ? '#020617' : '#ffffff',
        border: isDark ? '1px solid rgba(148, 163, 184, 0.6)' : '1px solid rgba(209, 213, 219, 0.9)',
        display: 'flex',
        flexDirection: 'column',
        zIndex: 999,
    },
    header: {
        padding: '0.75rem 1rem',
        background: isDark ? 'linear-gradient(135deg, #0f172a, #16a34a)' : 'linear-gradient(135deg, #22c55e, #16a34a)',
        color: '#ffffff',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        fontWeight: 600,
        fontSize: '0.95rem',
    },
    closeButton: {
        border: 'none',
        background: 'transparent',
        color: '#ffffff',
        fontSize: '1.1rem',
        cursor: 'pointer',
        padding: 0,
        lineHeight: 1,
    },
    body: {
        padding: '0.75rem',
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
    },
    messagesContainer: {
        flex: 1,
        overflowY: 'auto',
        padding: '0.25rem 0.1rem 0.5rem',
    },
    botMessageWrapper: {
        display: 'flex',
        justifyContent: 'flex-start',
        marginBottom: '0.35rem',
    },
    userMessageWrapper: {
        display: 'flex',
        justifyContent: 'flex-end',
        marginBottom: '0.35rem',
    },
    botMessage: {
        maxWidth: '85%',
        backgroundColor: isDark ? '#111827' : '#e5f9ec',
        color: isDark ? '#e5e7eb' : '#052e16',
        padding: '0.55rem 0.7rem',
        borderRadius: '12px',
        fontSize: '0.82rem',
        lineHeight: 1.4,
    },
    userMessage: {
        maxWidth: '85%',
        backgroundColor: isDark ? '#16a34a' : '#22c55e',
        color: '#ffffff',
        padding: '0.55rem 0.7rem',
        borderRadius: '12px',
        fontSize: '0.82rem',
        lineHeight: 1.4,
    },
    inputRow: {
        display: 'flex',
        gap: '0.35rem',
        borderTop: isDark ? '1px solid rgba(30, 64, 175, 0.5)' : '1px solid rgba(209, 213, 219, 0.9)',
        paddingTop: '0.35rem',
    },
    input: {
        flex: 1,
        borderRadius: '999px',
        border: isDark ? '1px solid rgba(148, 163, 184, 0.8)' : '1px solid rgba(209, 213, 219, 0.9)',
        padding: '0.45rem 0.75rem',
        fontSize: '0.82rem',
        outline: 'none',
        backgroundColor: isDark ? '#020617' : '#ffffff',
        color: isDark ? '#e5e7eb' : '#111827',
    },
    sendButton: {
        borderRadius: '999px',
        border: 'none',
        padding: '0.45rem 0.85rem',
        fontSize: '0.8rem',
        fontWeight: 600,
        backgroundColor: isDark ? '#16a34a' : '#22c55e',
        color: '#ffffff',
        cursor: 'pointer',
    },
});

export default Chatbot;
